name: Multi-Instance Deployment

on:
  push:
    branches: [ main ] # Trigger on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # This will run the steps below for both IPs in parallel
        server: [ "${{ secrets.EC2_HOST_1 }}", "${{ secrets.EC2_HOST_2 }}" ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Execute Remote Commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ matrix.server }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/project
            git pull origin main
